### PR TITLE
Fixed crash in Blender 2.93 where custom avatar converter for vircadi…

### PR DESCRIPTION
**Pull request by ksuprynowicz**
…a crashed when there were hidden armatures in the scene

### CODE REVIEW

**Comment by Menithal** [comment]
Cool stuff! I haven't dont the export process a bit so it was bound to break. Thanks for the patch!

**Comment by ksuprynowicz** [comment]
You're welcome and thanks for making this addon!
More patches coming soon :)
I'm fixing Apply Modifiers to Mesh With Shape Keys script right now. It will make porting avatars so much easier

**Comment by Menithal** [comment]
I havent gotten around to checking 2.9, did the patch i made for it back in 2.8 break again?

**Comment by Menithal** [comment]
Oh! I just checked, the origin branch I made out of it has been updated since I last looked at it. Probably better just to check if the new origin one works with the Metaverse plugin instead.

**Pull request merged**
